02/01/2023 10:25:59|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 10:25:59|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 10:26:01|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 10:53:51|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff535ba7490>: Failed to establish a new connection: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7ff535ba7490>: Failed to establish a new connection: [Errno 101] Network unreachable\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7ff535ba7490>: Failed to establish a new connection: [Errno 101] Network unreachable\'))'|
02/01/2023 10:53:54|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff535c06500>: Failed to establish a new connection: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7ff535c06500>: Failed to establish a new connection: [Errno 101] Network unreachable\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7ff535c06500>: Failed to establish a new connection: [Errno 101] Network unreachable\'))'|
02/01/2023 10:53:56|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 11:10:37|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 11:12:41|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 11:12:41|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 11:48:04|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 11:48:10|INFO    |root                            |BAZARR SignalR client for Radarr is now disconnected.|
02/01/2023 11:48:10|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 11:48:10|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 12:09:41|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 12:09:41|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 12:09:41|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 12:09:41|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 12:09:41|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 12:22:35|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 12:22:37|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 12:22:37|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 12:22:37|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 12:22:37|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 12:22:37|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 12:29:08|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 12:29:20|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 12:29:20|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 12:29:20|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 12:34:08|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 12:34:11|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 12:34:11|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 12:34:11|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 12:34:11|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 12:34:11|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 12:49:52|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
02/01/2023 13:52:13|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 13:52:13|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 13:52:13|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 13:52:14|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 13:57:59|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
02/01/2023 13:59:00|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 13:59:00|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 13:59:00|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 13:59:01|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 14:03:01|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
02/01/2023 15:33:27|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f977f3977c0>: Failed to establish a new connection: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f977f3977c0>: Failed to establish a new connection: [Errno -3] Try again\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f977f3977c0>: Failed to establish a new connection: [Errno -3] Try again\'))'|
02/01/2023 15:33:29|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 15:33:29|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 15:33:29|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 15:33:29|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 15:33:29|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 17:21:39|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 17:21:39|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 17:21:39|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 17:21:39|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 17:21:39|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 17:26:17|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 17:26:17|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 17:26:17|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 17:26:17|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 17:26:17|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 17:10:27|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:33|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:38|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:43|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:48|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:53|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:10:58|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:09|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:14|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:19|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:23|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:28|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:33|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:38|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:43|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:48|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:53|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:11:58|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:08|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:40|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:46|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:52|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:12:58|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:09|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:14|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:19|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:24|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:29|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:34|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:40|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:45|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:50|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:13:55|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:00|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:05|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:10|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:15|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:20|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:25|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:30|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:35|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:41|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:46|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:52|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:14:57|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:08|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:13|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:18|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:23|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:28|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:15:33|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 18:16:17|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 18:16:19|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:16:19|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 18:16:19|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 18:16:19|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 18:16:19|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 17:20:15|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:21|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:27|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:32|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:37|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:43|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:48|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:20:53|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:30:20|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:30:22|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 17:30:22|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 17:30:22|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 17:30:22|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 17:30:22|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 18:34:56|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 18:34:58|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:34:58|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 18:34:58|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 18:34:58|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 18:34:58|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 18:57:13|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 18:57:15|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:57:15|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 18:57:15|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 18:57:15|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 18:57:15|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:05:06|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:05:06|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:05:06|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:05:06|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:05:06|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:06:16|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:06:16|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:06:16|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:06:16|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:06:16|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:11:05|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:11:05|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:11:05|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:11:06|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:11:06|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:15:24|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:15:24|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:15:24|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:15:24|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:15:24|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
